name: Workflow for pull request on master version of Coq

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - coq-master

jobs:
  from-sources:
    if: ${{ github.event.action != 'labeled' || (github.event.action == 'labeled' && github.event.label.name == 'workflow') }}
    uses: ./.github/workflows/from-sources.yml
    with:
      image-version: ${{ github.base_ref }}
